auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /tmp/loki/chunks
      rules_directory: /tmp/loki/rules
  replication_factor: 1

schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 5m
  chunk_retain_period: 30s

storage_config:
  boltdb_shipper:
    active_index_directory: /tmp/loki/index
    cache_location: /tmp/loki/cache

compactor:
  working_directory: /tmp/loki/compactor
  compaction_interval: 10m

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true

frontend:
  log_queries_longer_than: 5s
  compress_responses: true

ruler:
  storage:
    type: local
    local:
      directory: /tmp/loki/rules