receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
processors:
  batch:
    timeout: 10s
    send_batch_size: 100
  attributes/otelcolflag:
    actions:
      - key: otelcolflag
        value: custom-attribute
        action: insert
exporters:
  otlp/tempo:
    endpoint: "tempo:4317"
    tls:
      insecure: true
  otlp/loki:
    endpoint: "loki:4317"
    tls:
      insecure: true
  prometheus:
    endpoint: ":8889"
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, attributes/otelcolflag]
      exporters: [otlp/tempo]
    metrics:
      receivers: [otlp]
      processors: [batch, attributes/otelcolflag]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      processors: [batch, attributes/otelcolflag]
      exporters: [otlp/loki]
