global:
  evaluation_interval: 30s
  scrape_interval: 5s
storage:
  tsdb:
    out_of_order_time_window: 30m
scrape_configs:
  - job_name: 'otelcol'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['otelcol:8889']